packages:
  - projects/*
  - packages/*

catalog:
  '@tailwindcss/postcss': ^4.1.18
  '@types/node': ^25.0.1
  eslint: ^9.39.1
  lucide-react: 0.561.0
  next: ^16.0.10
  next-themes: ^0.4.6
  postcss: ^8.5.6
  prettier: ^3.7.4
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  zod: ^4.1.13

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    babel-plugin-react-compiler: ^1.0.0
    react: ^19.2.3
    react-dom: ^19.2.3

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
