packages:
  - projects/*
  - packages/*

catalog:
  '@tailwindcss/postcss': ^4.1.11
  '@types/node': ^24.3.0
  eslint: ^9.32.0
  lucide-react: 0.540.0
  next: ^15.5.2
  next-themes: ^0.4.6
  postcss: ^8.5.6
  prettier: ^3.6.2
  tailwindcss: ^4.1.12
  typescript: ^5.9.3
  zod: ^4.1.5

catalogs:
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
