packages:
  - projects/*
  - packages/*

catalog:
  '@tailwindcss/postcss': ^4.1.16
  '@types/node': ^24.9.2
  eslint: ^9.39.0
  lucide-react: 0.552.0
  next: ^16.0.1
  next-themes: ^0.4.6
  postcss: ^8.5.6
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: ^19.2.0
    react-dom: ^19.2.0
    babel-plugin-react-compiler: ^1.0.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
