import '@workspace/ui/globals.css';

import React from 'react';
import { type Metadata } from 'next';
import { Toaster } from '@workspace/ui/components/sonner';
import { Navbar } from '@/components/navbar';
import { env } from '@/env';
import { AutumnProvider } from 'autumn-js/react';

export const metadata: Metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body>
				<AutumnProvider betterAuthUrl={env.NEXT_PUBLIC_BETTER_AUTH_URL}>
					<Navbar />
					<main>{children}</main>
					<Toaster position="bottom-left" />
				</AutumnProvider>
			</body>
		</html>
	);
}
