import '~/styles/globals.css';

import React from 'react';
import { type Metadata } from 'next';
import { Toaster } from '~/components/ui/sonner';
import { Navbar } from '~/components/navbar';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar />
        <main>{children}</main>
        <Toaster position="bottom-left" />
      </body>
    </html>
  );
}
