import "~/styles/globals.css";

import { type Metadata } from "next";
import { AuthenticatedNavbar } from "~/components/authenticated-navbar";
import { GuestNavbar } from "~/components/guest-navbar";
import { Toaster } from "~/components/ui/sonner";
import { auth } from "~/lib/auth";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en">
      <body>
        {session ? <AuthenticatedNavbar /> : <GuestNavbar />}
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
